[tool.poetry]
name = "cloudconnectlib"
version = "2.0.3"
description = "APP Cloud Connect"
authors = ["Addon Factory template <addonfactory@splunk.com>"]
license = "APACHE-2.0"

[tool.poetry.dependencies]
python = "^3.7"
jsonschema = "2.6.0"
jinja2 = "2.10.1"
jsonpath-rw = "1.4.0"
httplib2 = "0.19.1"
splunk-sdk = "1.6.15"
sortedcontainers = "2.3.0"
munch = "2.3.2"
splunktaucclib = "4.1.2"
solnlib = "3.0.5"
six = "future"
future = "*"
configparser = "^5.0.2"
requests = "^2.25.1"
splunktalib = "^1.2.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
